[package]
name = "rust_pathtracer"
version = "0.1.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
rayon = "1.3.0"
toml = "0.5"
num_cpus = "1.12.0"
serde = { version = "1.0.105", features = ["derive"] }


[build-dependencies]
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.50"

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0
